# -s flag checks that the file is > 0 bytes
[[ -s "$HOME/.tokens" ]] && source "$HOME/.tokens"

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
eval "$(starship init bash)"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
eval "$(mise activate bash)"

export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
. "$HOME/.cargo/env"

# >>> gitlab-pat-rotate >>>
[ -f "$HOME/.config/gitlab-pat/env.sh" ] && . "$HOME/.config/gitlab-pat/env.sh"
# <<< gitlab-pat-rotate <<<
