export BASH_SILENCE_DEPRECATION_WARNING=1
export EDITOR=nvim
export PATH=$HOME/.local/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/Cellar:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH"
export PATH=$PATH.~/.rbenv/shims
export PATH=/Applications/SnowSQL.app/Contents/MacOS:$PATH
export PATH=/Applications/Postgres.app/Contents/Versions/12/bin:$PATH
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
export GOPATH=$HOME/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PYTEST_ADDOPTS='-s'
export CLICOLOR=1
export TERM=xterm-256color
export LSCOLORS=GxFxCxDxBxegedabagaced
export CLICOLOR=1
export TERM=xterm-256color
export LSCOLORS=GxFxCxDxBxegedabagaced
export SCALA_HOME="/usr/local/opt/scala/idea"
bind 'set show-all-if-ambiguous on'
bind 'set completion-ignore-case on'
bind 'TAB:menu-complete'
export HISTCONTROL=ignoreboth
source ~/.dotfiles/bash_base_config/fzf_profile.sh
source ~/.dotfiles/bash_base_config/git_prompt.sh
source ~/.dotfiles/bash_base_config/prompt.sh
source ~/.dotfiles/bash_base_config/aliases.sh
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

if [ -f ~/.config/exercism/exercism_completion.bash ]; then
  . ~/.config/exercism/exercism_completion.bash
fi
eval "$(rbenv init -)"
eval "$(pyenv init -)"
if which pyenv-virtualenv-init > /dev/null; then
  eval "$(pyenv virtualenv-init -)"
fi

function docker_clean {
  docker rmi $(docker images -f "dangling=true" -q -f)
}

function aws_shell() {
  pyenv local 3.6.9
  aws-jumpcloud exec $1 -- aws-shell
}
