# Amazon Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.pre.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.pre.bash"
# -s flag checks that the file is > 0 bytes
[[ -s "$HOME/.tokens" ]] && source "$HOME/.tokens"

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
eval "$(starship init bash)"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
eval "$(mise activate bash)"
source ~/.fzf/shell/key-bindings.bash
source ~/.fzf/shell/completion.bash

export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

export PATH="/Applications/Fortify/Fortify_SCA_24.2.0/bin:$PATH"
. <(asdf completion bash)
. $(brew --prefix asdf)/libexec/asdf.sh
. ~/.asdf/plugins/java/set-java-home.bash
# Amazon Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.post.bash" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/bash_profile.post.bash"
