source ~/.dotfiles/bash/fzf_profile.sh
source ~/.dotfiles/bash/git_profile.sh
source ~/.dotfiles/bash/colors.sh
source ~/.dotfiles/bash/aliases.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

if [ -f ~/.config/exercism/exercism_completion.bash ]; then
  . ~/.config/exercism/exercism_completion.bash
fi
