export GITAWAREPROMPT=~/.bash/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"
source ~/.dotfiles/bash/git_profile.sh
source ~/.dotfiles/bash/colors.sh
source ~/.dotfiles/bash/fzf_profile.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f $(brew --prefix)/etc/bash_completion ]; then
. $(brew --prefix)/etc/bash_completion
fi

alias bash='atom ~/.dotfiles/bash/bash_profile.sh'
alias reload='source ~/.dotfiles/bash/bash_profile.sh'
alias vim='nvim'
alias vi='nvim'
alias ls="ls -GFh"
alias show='ls'
alias c='clear'
alias home="cd ~"
alias up='cd ..'
alias be='bundle exec'
alias back='cd -'
alias opencov="open coverage/index.html"
alias mod1="cd ~/Turing/1module"
alias mod2="cd ~/Turing/2module"
alias mod3="cd ~/Turing/3module"
alias mod4="cd ~/Turing/4module"
alias drills="cd ~/exercism"
alias browse="hub browse"
alias g='git'
alias ga="git add ."
alias gs="git status"
alias gcm="git commit -m"
alias gpo="git push origin"
alias gb="git branch"
alias gc="git checkout"
alias gmaster="git checkout master"
alias gac="git add . && git commit -m"
alias gpom="git pull origin master"
alias showdotfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hidedotfiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias today="open http://today.turing.io"
alias dotfiles="~/.dotfiles"
alias runexpress="DEBUG=myapp:* npm start --scripts-prepend-node-path"
