[[ -s ~/.bashrc ]] && source ~/.bashrc
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"
source ~/.dotfiles/bash/git_profile.sh
source ~/.dotfiles/bash/colors.sh
source ~/.dotfiles/bash/fzf_profile.sh
export PATH=$PATH:/path/to/geckodriver
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/Cellar:$PATH"
eval "$(rbenv init -)"
export CLICOLOR=1
export TERM=xterm-256color
export LSCOLORS=GxFxCxDxBxegedabagaced
export PATH=$PATH.~/.rbenv/shims
export GOPATH=$HOME/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export EDITOR=nvim
export HISTCONTROL=ignoreboth:erasedups
set show-all-if-ambiguous on
set completion-ignore-case on
bind 'TAB:menu-complete'

alias bash='atom ~/.dotfiles/bash/bash_profile'
alias reload='source ~/.dotfiles/bash/bash_profile'
alias vim='nvim'
alias vi='nvim'
alias ls="ls -GFh"
alias show='ls'
alias c='clear'
alias home="cd ~"
alias up='cd ..'
alias be='bundle exec'
alias back='cd -'
alias opencov="open coverage/index.html"
alias mod1="cd ~/Turing/1module"
alias mod2="cd ~/Turing/2module"
alias mod3="cd ~/Turing/3module"
alias mod4="cd ~/Turing/4module"
alias drills="cd ~/exercism"
alias browse="hub browse"
alias g='git'
alias ga="git add ."
alias gs="git status"
alias gcm="git commit -m"
alias gpo="git push origin"
alias gb="git branch"
alias gc="git checkout"
alias gmaster="git checkout master"
alias gac="git add . && git commit -m"
alias gpom="git pull origin master"
alias showdotfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hidedotfiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias today="open http://today.turing.io"
alias dotfiles="~/.dotfiles"
alias runexpress="DEBUG=myapp:* npm start --scripts-prepend-node-path"

function gpush() {
  BRANCH=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
  git push -u origin "${BRANCH}"
}
function lazygit() {
  BRANCH=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
  git add .
  git commit -m "$1"
  git push -u origin "${BRANCH}"
}

function lazyrails() {
  rails new "$1" -d postgresql --skip-turbolinks --skip-spring -T
  cd "$1"
  echo "
  group :test do
  gem 'rack_session_access'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers'
 end
  group :development, :test do
    gem 'rspec-rails'
    gem 'database_cleaner'
    gem 'byebug', platform: :mri
    gem 'factory_girl_rails'
    gem 'pry'
    gem 'pry-byebug'
  end " >> Gemfile
  bundle install
  rails g rspec:install
}

function md () { mkdir -p "$@" && cd "$@";}

function codi() {
  local syntax="${1:-python}"
  shift
  vim -c \
    "let g:startify_disable_at_vimenter = 1 |\
    set bt=nofile ls=0 noru nonu nornu |\
    hi ColorColumn ctermbg=NONE |\
    hi VertSplit ctermbg=NONE |\
    hi NonText ctermfg=0 |\
    Codi $syntax" "$@"
}

##
# Your previous /Users/robertsmith/.bash_profile file was backed up as /Users/robertsmith/.bash_profile.macports-saved_2017-03-06_at_19:57:41
##

# MacPorts Installer addition on 2017-03-06_at_19:57:41: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
